name: 'goKakashi Scan'
description: 'A GitHub Action to trigger on demand and store image scans reports.'
author: 'goKakashi'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  api_host:
    description: 'The base URL of the goKakashi API'
    required: true
  api_token:
    description: 'API token for authentication with goKakashi'
    required: true
  image_name:
    description: 'The image to scan'
    required: true
  severity:
    description: 'Comma-separated list of severity levels to report'
    required: true
    default: 'CRITICAL'
  publish:
    description: 'The publish path for the scan report'
    required: false
  fail_on_severity:
    description: 'Comma-separated list of severity levels to fail the job on (e.g., CRITICAL,HIGH)'
    required: false
    default: 'CRITICAL'

outputs:
  report_url:
    description: 'URL of the scan report'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: .github/actions/gokakashi-scan

    - name: Install dependencies
      run: npm ci
      working-directory: .github/actions/gokakashi-scan
      shell: bash

    - name: Run goKakashi scan
      run: node index.js
      shell: bash
      working-directory: .github/actions/gokakashi-scan
      env:
        INPUT_API_HOST: ${{ inputs.api_host }}
        INPUT_API_TOKEN: ${{ inputs.api_token }}
        INPUT_IMAGE_NAME: ${{ inputs.image_name }}
        INPUT_SEVERITY: ${{ inputs.severity }}
        INPUT_PUBLISH: ${{ inputs.publish }}
        INPUT_FAIL_ON_SEVERITY: ${{ inputs.fail_on_severity }}