name: 'goKakashi Scan'
description: 'A GitHub Action to trigger on demand and store image scans reports.'
author: 'goKakashi'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  api_host:
    description: 'The base URL of the goKakashi API'
    required: true
  api_token:
    description: 'API token for authentication with goKakashi'
    required: true
  image_name:
    description: 'The image to scan'
    required: true
  severity:
    description: 'Comma-separated list of severity levels to report'
    required: true
    default: 'CRITICAL'
  publish:
    description: 'The publish path for the scan report'
    required: false
  fail_on_severity:
    description: 'Comma-separated list of severity levels to fail the job on (e.g., CRITICAL,HIGH)'
    required: false
    default: 'CRITICAL'

outputs:
  report_url:
    description: 'URL of the scan report'

runs:
  using: 'node20'
  main: 'index.js'